<?php

namespace MasterPeace\Bundle\QuizBundle\Repository;

/**
 * QuizResultAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizResultAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
