language: php

php:
    - 7.0

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - mysql -e 'create database symfony;'

script:
    - php bin/console doctrine:schema:drop --force
    - php bin/console doctrine:schema:create
    - php bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load --no-interaction