language: php

php:
    - 7.0

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create
  - composer install
  - php bin/console doctrine:schema:drop --force
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 src