language: php

php:
    - 7.0

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install
  - composer require satooshi/php-coveralls
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:drop --force
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:schema:validate
  - php bin/console doctrine:fixtures:load --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  slack: nfqakademija:79ZFHa5rDxOqUtKplVDOcfnS