imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: lt

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "%database_server_version%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS USER BUNDLE CONFIGURATIONS #
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MasterPeace\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: MasterPeace\Bundle\UserBundle\Form\RegistrationType

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true

# EASY ADMIN CONFIGURATIONS #
easy_admin:
    site_name: 'UpRead-Admin'
    design:
        color_scheme: 'dark'
        brand_color: '#333333'
    entities:
        User:
            class: MasterPeace\Bundle\UserBundle\Entity\User
            list:
                fields:
                    - { property: 'username', label: 'Vartotojo vardas' }
                    - { property: 'name', label: 'Vardas' }
                    - { property: 'surname', label: 'Pavardė' }
                    - { property: 'email', label: 'El. paštas' }
                    - { property: 'lastLogin', label: 'Paskutinis prisijungimas' }
                    - { property: 'roles', label: 'Rolės' }
            form:
                fields:
                    - { property: 'username', label: 'Vartotojo vardas' }
                    - { property: 'name', label: 'Vardas' }
                    - { property: 'surname', label: 'Pavardė' }
                    - { property: 'email', label: 'El. paštas' }
                    - { property: 'lastLogin', label: 'Paskutinis prisijungimas'}
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, label: 'Slaptažodis' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Studentas': 'ROLE_STUDEN', 'Mokytojas': 'ROLE_TEACHER', 'Administratorius': 'ROLE_ADMIN' } }, label: 'Rolė' }
            label: 'User'
            list:
                title: 'User manager'
        Classroom:
            class: MasterPeace\Bundle\UserBundle\Entity\Classroom
            form:
                fields:
                    - { property: 'title', label: 'Klasės pavadinimas' }
                    - { property: 'teacher', label: 'Mokytojas' }
                    - { property: 'students', label: 'Studentai' }
            label: 'Classroom'
            list:
                title: 'Classroom manager'
                fields:
                    - { property: 'title', label: 'Klasės pavadinimas' }
                    - { property: 'teacher', label: 'Mokytojas' }
                    - { property: 'students', label: 'Studentai' }
        ClassroomStudent:
            class: MasterPeace\Bundle\UserBundle\Entity\ClassroomStudent
            form:
                fields:
                    - { property: 'classroom', label: 'Klasė' }
                    - { property: 'student', label: 'Mokinys' }
            label: 'Classroom Student'
            list:
                title: 'Classroom Student manager'
                fields:
                    - { property: 'classroom', label: 'Klasės ID' }
                    - { property: 'student', label: 'Priskitas Mokinys' }
        Book:
            class: MasterPeace\Bundle\BookBundle\Entity\Book
            form:
                fields:
                    - { property: 'title', label: 'Knygos pavadinimas' }
                    - { property: 'author', label: 'Autorius' }
                    - { property: 'year', label: 'Metai' }
                    - { property: 'publisher', label: 'Leidėjas' }
                    - { property: 'cover', label: 'Viršelis' }
                    - { property: 'isbnCode', label: 'ISBN' }
            label: 'Book'
            list:
                title: 'Book manager'
                fields:
                    - { property: 'title', label: 'Knygos pavadinimas' }
                    - { property: 'author', label: 'Autorius' }
                    - { property: 'year', label: 'Metai' }
                    - { property: 'publisher', label: 'Leidėjas' }
                    - { property: 'cover', label: 'Viršelis' }
                    - { property: 'isbnCode', label: 'ISBN' }
        Quiz:
            class: MasterPeace\Bundle\QuizBundle\Entity\Quiz
            form:
                fields:
                    - { property: 'title', label: 'Pavadinimas' }
                    - { property: 'teacher', label: 'Mokytojas' }
                    - { property: 'book', label: 'Knyga' }
                    - { property: 'questions', label: 'Klausimai' }
            label: 'Quiz'
            list:
                title: 'Quiz manager'
                fields:
                    - { property: 'title', label: 'Pavadinimas' }
                    - { property: 'teacher', label: 'Mokytojas' }
                    - { property: 'book', label: 'Knyga' }
                    - { property: 'questions', label: 'Klausimai' }
        Question:
            class: MasterPeace\Bundle\BookBundle\Entity\Question
            form:
                fields:
                    - { property: 'title', label: 'Pavadinimas' }
                    - { property: 'book', label: 'Knyga' }
                    - { property: 'answers', label: 'Atsakymai' }

            label: 'Question'
            list:
                title: 'Question manager'
                fields:
                    - { property: 'title', label: 'Pavadinimas' }
                    - { property: 'book', label: 'Knyga' }
                    - { property: 'answers', label: 'Atsakymai' }
        Answer:
            class: MasterPeace\Bundle\BookBundle\Entity\Answer
            form:
                fields:
                    - { property: 'title', label: 'Klausimo pavadinimas' }
                    - { property: 'question', label: 'Klausimas' }
                    - { property: 'correct', label: 'Teisingas' }
            label: 'Answer'
            list:
                title: 'Answer manager'
                fields:
                    - { property: 'question', label: 'Klausimo ID' }
                    - { property: 'title', label: 'Klausimo pavadinimas' }
                    - { property: 'correct', label: 'Teisingas' }
        QuizResult:
            class: MasterPeace\Bundle\QuizBundle\Entity\QuizResult
            form:
                fields:
                    - { property: 'student', label: 'Mokinys' }
                    - { property: 'quiz', label: 'Klausimyno ID' }
            label: 'Quiz Result'
            list:
                title: 'Quiz result manager'
                fields:
                    - { property: 'student', label: 'Mokinys' }
                    - { property: 'quiz', label: 'Klausimyno ID' }
        QuizResultAnswer:
            class: MasterPeace\Bundle\QuizBundle\Entity\QuizResultAnswer
            form:
                fields:
                    - { property: 'quizResult', label: 'Rezultato ID' }
                    - { property: 'answer', label: 'Atsakymas' }
                    - { property: 'question', label: 'Klausimas' }
            label: 'Quiz Result Answer'
            list:
                title: 'Quiz result answer manager'
                fields:
                    - { property: 'quizResult', label: 'Rezultato ID' }
                    - { property: 'answer', label: 'Atsakymas' }
                    - { property: 'question', label: 'Klausimas' }
    edit:
        actions: ['show']
    list:
        actions: ['edit', 'search']