imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: lt

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: "%database_server_version%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS USER BUNDLE CONFIGURATIONS #
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MasterPeace\Bundle\UserBundle\Entity\User
    registration:
        form:
            type: MasterPeace\Bundle\UserBundle\Form\RegistrationType

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true

# EASY ADMIN CONFIGURATIONS #
easy_admin:
    site_name: 'UpRead-Admin'
    design:
        color_scheme: 'dark'
        brand_color: '#333333'
    entities:
        User:
            class: MasterPeace\Bundle\UserBundle\Entity\User
            list:
                title: 'title.user'
                fields:
                    - { property: 'username', label: 'form.user.username' }
                    - { property: 'name', label: 'form.user.name' }
                    - { property: 'surname', label: 'form.user.surname' }
                    - { property: 'email', label: 'form.user.email' }
                    - { property: 'lastLogin', label: 'form.user.lastLogin' }
                    - { property: 'roles', label: 'form.user.roles' }
            form:
                fields:
                    - { property: 'username', label: 'list.user.username' }
                    - { property: 'name', label: 'list.user.name' }
                    - { property: 'surname', label: 'list.user.surname' }
                    - { property: 'email', label: 'list.user.email' }
                    - { property: 'plainPassword', type: 'text', type_options: { required: false }, label: 'Slaptažodis' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Studentas': 'ROLE_STUDEN', 'Mokytojas': 'ROLE_TEACHER', 'Administratorius': 'ROLE_ADMIN' } }, label: 'Rolė' }
            label: 'label.user'
        Classroom:
            class: MasterPeace\Bundle\UserBundle\Entity\Classroom
            form:
                fields:
                    - { property: 'title', label: 'form.classroom.title' }
                    - { property: 'teacher', label: 'form.classroom.teacher' }
                    - { property: 'students', label: 'form.classroom.students' }
            label: 'label.classroom'
            list:
                title: 'title.classroom'
                fields:
                    - { property: 'title', label: 'list.classroom.title' }
                    - { property: 'teacher', label: 'list.classroom.teacher' }
                    - { property: 'students', label: 'list.classroom.students' }
        ClassroomStudent:
            class: MasterPeace\Bundle\UserBundle\Entity\ClassroomStudent
            form:
                fields:
                    - { property: 'classroom', label: 'form.classroomstudent.classroom' }
                    - { property: 'student', label: 'form.classroomstudent.student' }
            label: 'label.classroomstudent'
            list:
                title: 'title.classroomstudent'
                fields:
                    - { property: 'classroom', label: 'list.classroomstudent.classroom' }
                    - { property: 'student', label: 'list.classroomstudent.student' }
        Book:
            class: MasterPeace\Bundle\BookBundle\Entity\Book
            form:
                fields:
                    - { property: 'title', label: 'form.book.title' }
                    - { property: 'author', label: 'form.book.author' }
                    - { property: 'year', label: 'form.book.year' }
                    - { property: 'publisher', label: 'form.book.publisher' }
                    - { property: 'cover', label: 'form.book.cover' }
                    - { property: 'isbnCode', label: 'form.book.isbncode' }
            label: 'label.book'
            list:
                title: 'title.book'
                fields:
                    - { property: 'title', label: 'list.book.title' }
                    - { property: 'author', label: 'list.book.author' }
                    - { property: 'year', label: 'list.book.year' }
                    - { property: 'publisher', label: 'list.book.publisher' }
                    - { property: 'cover', label: 'list.book.cover' }
                    - { property: 'isbnCode', label: 'list.book.isbncode' }
        Quiz:
            class: MasterPeace\Bundle\QuizBundle\Entity\Quiz
            form:
                fields:
                    - { property: 'title', label: 'form.quiz.title' }
                    - { property: 'teacher', label: 'form.quiz.teacher' }
                    - { property: 'book', label: 'form.quiz.book' }
                    - { property: 'questions', label: 'form.quiz.questions' }
            label: 'label.quiz'
            list:
                title: 'title.quiz'
                fields:
                    - { property: 'title', label: 'list.quiz.title' }
                    - { property: 'teacher', label: 'list.quiz.teacher' }
                    - { property: 'book', label: 'list.quiz.book' }
                    - { property: 'questions', label: 'list.quiz.questions' }
        Question:
            class: MasterPeace\Bundle\BookBundle\Entity\Question
            form:
                fields:
                    - { property: 'title', label: 'form.question.title' }
                    - { property: 'book', label: 'form.question.book' }
                    - { property: 'answers', label: 'form.question.answers' }

            label: 'label.question'
            list:
                title: 'title.question'
                fields:
                    - { property: 'title', label: 'list.question.title' }
                    - { property: 'book', label: 'list.question.book' }
                    - { property: 'answers', label: 'list.question.answers' }
        Answer:
            class: MasterPeace\Bundle\BookBundle\Entity\Answer
            form:
                fields:
                    - { property: 'title', label: 'form.answer.title' }
                    - { property: 'question', label: 'form.answer.question' }
                    - { property: 'correct', label: 'form.answer.correct' }
            label: 'label.answer'
            list:
                title: 'title.answer'
                fields:
                    - { property: 'title', label: 'list.answer.title' }
                    - { property: 'question', label: 'list.answer.question' }
                    - { property: 'correct', label: 'list.answer.correct' }
        QuizResult:
            class: MasterPeace\Bundle\QuizBundle\Entity\QuizResult
            label: 'label.quizresult'
            list:
                title: 'title.quizresult'
                fields:
                    - { property: 'student', label: 'list.quizresult.student' }
                    - { property: 'quiz', label: 'list.quizresult.quiz' }
        QuizResultAnswer:
            class: MasterPeace\Bundle\QuizBundle\Entity\QuizResultAnswer
            label: 'label.quizresultanswer'
            list:
                title: 'title.quizresultanswer'
                fields:
                    - { property: 'quizResult', label: 'list.quizresultanswer.quizresult' }
                    - { property: 'answer', label: 'list.quizresultanswer.answer' }
                    - { property: 'question', label: 'list.quizresultanswer.question' }
    edit:
        actions: ['show']
    list:
        actions: ['edit', 'search']