book:
    resource: "@MasterPeaceBookBundle/Controller/"
    type:     annotation
    prefix:   /book/

masterpeace_user:
    resource: "@MasterPeaceUserBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
