quiz:
    resource: "@MasterPeaceQuizBundle/Controller/"
    type:     annotation
    prefix:   /quiz/

book:
    resource: "@MasterPeaceBookBundle/Controller/"
    type:     annotation
    prefix:   /book/

user:
    resource: "@MasterPeaceUserBundle/Controller/"
    type:     annotation
    prefix:   /user/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
