classroom:
    resource: "@MasterPeaceClassroomBundle/Controller/"
    type:     annotation
    prefix:   /classroom

book:
    resource: "@MasterPeaceBookBundle/Controller/"
    type:     annotation
    prefix:   /book

quiz:
    resource: "@MasterPeaceQuizBundle/Controller/"
    type:     annotation
    prefix:   /quiz

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    resource: "@MasterPeaceUpReadBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
