book:
    resource: "@MasterPeaceBookBundle/Controller/"
    type:     annotation
    prefix:   /book/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
    path:      /
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_security_logout:
    path:      /logout
    defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }
