book:
    resource: "@MasterPeaceBookBundle/Controller/"
    type:     annotation
    prefix:   /book/

classroom:
    resource: "@MasterPeaceUserBundle/Controller/ClassroomController.php"
    type:     annotation
    prefix:   /classroom/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    resource: "@MasterPeaceUpReadBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
