security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_STUDENT:     ROLE_STUDENT
        ROLE_TEACHER:     [ROLE_STUDENT, ROLE_TEACHER]
        ROLE_ADMIN:       [ROLE_STUDENT, ROLE_TEACHER, ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secure_area:
            pattern:  ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login

            logout:
                path:   /logout
                target: /


        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # TODO add separate paths for student and teacher users
        - { path: ^/*, role: [ROLE_ADMIN] }
        - { path: ^/admin/, role: ROLE_ADMIN }
