security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /usercheck
            logout:
                path: fos_user_security_logout
            anonymous: true

    access_control:
        - { path: ^/teacher, role: ROLE_TEACHER }
        - { path: ^/student, role: ROLE_STUDENT }
        - { path: ^/logout$, role: [ROLE_TEACHER, ROLE_STUDENT] }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
