# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# security:
#
#     # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_STUDENT:     ROLE_STUDENT
        ROLE_USER:        [ROLE_STUDENT, ROLE_USER]
        ROLE_ADMIN:       [ROLE_STUDENT, ROLE_USER, ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_STUDENT, ROLE_USER, ROLE_ADMI, ROLE_SUPER_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        student_area:
            pattern:  ^/student
            anonymous: ~
            form_login:
                check_path: /student/login_check
                login_path: /student/login
            logout:
                path:   /student/logout
                target: /

        teacher_area:
                    pattern:  ^/teacher
                    anonymous: ~
                    form_login:
                        check_path: /teacher/login_check
                        login_path: /teacher/login
                    logout:
                        path:   /teacher/logout
                        target: /
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/student/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/teacher/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
