services:
    master_peace_quiz.form_transformer.answer:
        class: MasterPeace\Bundle\QuizBundle\Form\Transformer\AnswerTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    master_peace_quiz.form_type.answer_choice:
        class: MasterPeace\Bundle\QuizBundle\Form\AnswerChoiceType
        arguments: ["@master_peace_quiz.form_transformer.answer"]
        tags:
            - { name: form.type }