todo_list:
    path: /
    defaults: { _controller: "TodoBundle:Todo:list" }

todo_create:
    path: /create
    defaults: { _controller: "TodoBundle:Todo:create" }

todo_edit:
    path: /edit/{id}
    defaults: { _controller: "TodoBundle:Todo:edit" }

todo_details:
    path: /details/{id}
    defaults: { _controller: "TodoBundle:Todo:details" }

todo_delete:
    path: /delete/{id}
    defaults: { _controller: "TodoBundle:Todo:delete" }
